/* eslint-disable @typescript-eslint/no-explicit-any */
export const queryMock = {
  site_id: "MLB",
  query: "livro",
  paging: {
    total: 921829,
    offset: 0,
    limit: 2,
    primary_results: 1000,
  },
  results: [
    {
      id: "MLB923744806",
      site_id: "MLB",
      title: "Pequeno Principe, O",
      seller: {
        id: 263929924,
        permalink: "http://perfil.mercadolivre.com.br/LIVRARIACULTURACULTURA",
        power_seller_status: "platinum",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 80.83,
      currency_id: "BRL",
      available_quantity: 500,
      sold_quantity: 500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_pro",
      stop_time: "2037-10-08T11:20:36.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-923744806-pequeno-principe-o-_JM",
      thumbnail:
        "http://mlb-s1-p.mlstatic.com/835599-MLB26167839876_102017-I.jpg",
      accepts_mercadopago: true,
      installments: null,
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-41",
        city_name: "Guarulhos",
      },
      shipping: {
        free_shipping: true,
        mode: "me1",
        tags: [],
        logistic_type: "default",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-41",
          name: "Guarulhos",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          values: [
            {
              id: null,
              name: "CAMINHO SUAVE ED.",
              struct: null,
              source: 252977589148881,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 252977589148881,
          id: "BRAND",
          value_id: null,
          value_struct: null,
          attribute_group_name: "Outros",
          name: "Marca",
          value_name: "CAMINHO SUAVE ED.",
        },
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          attribute_group_name: "Outros",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 1,
          value_id: "2230284",
          value_name: "Novo",
          value_struct: null,
        },
        {
          id: "MODEL",
          name: "Modelo",
          value_id: null,
          value_name: "Brochura",
          values: [
            {
              name: "Brochura",
              struct: null,
              source: 252977589148881,
              id: null,
            },
          ],
          value_struct: null,
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 252977589148881,
        },
      ],
      differential_pricing: {
        id: 33580182,
      },
      original_price: null,
      category_id: "MLB437616",
      official_store_id: 1140,
      catalog_product_id: null,
      tags: [
        "brand_verified",
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB918281211",
      site_id: "MLB",
      title: "Diário De Anne Frank Livro Novo Lacrado Com Fotos Autenticas",
      seller: {
        id: 207333581,
        permalink: "http://perfil.mercadolivre.com.br/SPMIX+SHOP",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
        eshop: {
          nick_name: "SPMIX SHOP",
          eshop_rubro: null,
          eshop_id: 263849,
          eshop_locations: [],
          site_id: "MLB",
          eshop_logo_url:
            "http://resources.mlstatic.com/eshops/207333581v804e60.png",
          eshop_status_id: 1,
          seller: 207333581,
          eshop_experience: 0,
        },
      },
      price: 21.3,
      currency_id: "BRL",
      available_quantity: 3,
      sold_quantity: 500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2040-01-18T21:32:05.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-918281211-diario-de-anne-frank-livro-novo-lacrado-com-fotos-autenticas-_JM",
      thumbnail:
        "http://mlb-s2-p.mlstatic.com/761859-MLB31712575492_082019-I.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 4,
        amount: 5.77,
        rate: 8.31,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-31",
        city_name: "Osasco",
      },
      shipping: {
        free_shipping: false,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-31",
          name: "Osasco",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          value_id: "2230284",
          value_name: "Novo",
          values: [
            {
              source: 1,
              id: "2230284",
              name: "Novo",
              struct: null,
            },
          ],
          attribute_group_name: "Outros",
          source: 1,
          name: "Condição do item",
          value_struct: null,
          attribute_group_id: "OTHERS",
          id: "ITEM_CONDITION",
        },
      ],
      original_price: null,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "dragged_bids_and_visits",
        "poor_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB1234567890",
      site_id: "MLB",
      title: "1984 - George Orwell - Edição Especial",
      seller: {
        id: 123456789,
        permalink: "http://perfil.mercadolivre.com.br/LIVRARIA_CLASSICOS",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 45.9,
      currency_id: "BRL",
      available_quantity: 150,
      sold_quantity: 890,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-06-15T10:30:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-1234567890-1984-george-orwell-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/1984-cover-image.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 6,
        amount: 7.65,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-RJ",
        state_name: "Rio de Janeiro",
        city_id: "BR-RJ-01",
        city_name: "Rio de Janeiro",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-RJ",
          name: "Rio de Janeiro",
        },
        city: {
          id: "BR-RJ-01",
          name: "Rio de Janeiro",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 59.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB9876543210",
      site_id: "MLB",
      title: "Harry Potter E A Pedra Filosofal - J.K. Rowling",
      seller: {
        id: 987654321,
        permalink: "http://perfil.mercadolivre.com.br/MEGALIVRARIA",
        power_seller_status: "platinum",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 34.9,
      currency_id: "BRL",
      available_quantity: 200,
      sold_quantity: 1500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_pro",
      stop_time: "2039-03-20T14:45:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-9876543210-harry-potter-pedra-filosofal-_JM",
      thumbnail: "http://mlb-s2-p.mlstatic.com/harry-potter-1-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 3,
        amount: 11.63,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-MG",
        state_name: "Minas Gerais",
        city_id: "BR-MG-01",
        city_name: "Belo Horizonte",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: [],
        logistic_type: "default",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-MG",
          name: "Minas Gerais",
        },
        city: {
          id: "BR-MG-01",
          name: "Belo Horizonte",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: null,
      category_id: "MLB437616",
      official_store_id: 2001,
      catalog_product_id: null,
      tags: [
        "brand_verified",
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "best_seller",
      ],
    },
    {
      id: "MLB5555555555",
      site_id: "MLB",
      title: "O Senhor Dos Anéis - A Sociedade Do Anel",
      seller: {
        id: 555555555,
        permalink: "http://perfil.mercadolivre.com.br/LIVROS_FANTASTICOS",
        power_seller_status: "silver",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 52.9,
      currency_id: "BRL",
      available_quantity: 85,
      sold_quantity: 650,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-12-10T16:20:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-5555555555-senhor-aneis-sociedade-anel-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/lotr-fellowship-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 10,
        amount: 5.29,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-RS",
        state_name: "Rio Grande do Sul",
        city_id: "BR-RS-01",
        city_name: "Porto Alegre",
      },
      shipping: {
        free_shipping: false,
        mode: "me1",
        tags: [],
        logistic_type: "default",
        store_pick_up: true,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-RS",
          name: "Rio Grande do Sul",
        },
        city: {
          id: "BR-RS-01",
          name: "Porto Alegre",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 64.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: ["good_quality_picture", "immediate_payment", "cart_eligible"],
    },
    {
      id: "MLB7777777777",
      site_id: "MLB",
      title: "Dom Casmurro - Machado de Assis - Capa Dura",
      seller: {
        id: 777777777,
        permalink: "http://perfil.mercadolivre.com.br/LITERATURA_BRASILEIRA",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 29.9,
      currency_id: "BRL",
      available_quantity: 120,
      sold_quantity: 430,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-08-25T11:00:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-7777777777-dom-casmurro-machado-assis-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/dom-casmurro-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 5,
        amount: 5.98,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-50",
        city_name: "Campinas",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-50",
          name: "Campinas",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
        {
          id: "BOOK_GENRE",
          name: "Gênero do livro",
          value_name: "Literatura Brasileira",
          values: [
            {
              id: "2271780",
              name: "Literatura Brasileira",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2271780",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 39.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "classic",
      ],
    },

    {
      id: "MLB923744806",
      site_id: "MLB",
      title: "Pequeno Principe, O",
      seller: {
        id: 263929924,
        permalink: "http://perfil.mercadolivre.com.br/LIVRARIACULTURACULTURA",
        power_seller_status: "platinum",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 80.83,
      currency_id: "BRL",
      available_quantity: 500,
      sold_quantity: 500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_pro",
      stop_time: "2037-10-08T11:20:36.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-923744806-pequeno-principe-o-_JM",
      thumbnail:
        "http://mlb-s1-p.mlstatic.com/835599-MLB26167839876_102017-I.jpg",
      accepts_mercadopago: true,
      installments: null,
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-41",
        city_name: "Guarulhos",
      },
      shipping: {
        free_shipping: true,
        mode: "me1",
        tags: [],
        logistic_type: "default",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-41",
          name: "Guarulhos",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          values: [
            {
              id: null,
              name: "CAMINHO SUAVE ED.",
              struct: null,
              source: 252977589148881,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 252977589148881,
          id: "BRAND",
          value_id: null,
          value_struct: null,
          attribute_group_name: "Outros",
          name: "Marca",
          value_name: "CAMINHO SUAVE ED.",
        },
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          attribute_group_name: "Outros",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 1,
          value_id: "2230284",
          value_name: "Novo",
          value_struct: null,
        },
        {
          id: "MODEL",
          name: "Modelo",
          value_id: null,
          value_name: "Brochura",
          values: [
            {
              name: "Brochura",
              struct: null,
              source: 252977589148881,
              id: null,
            },
          ],
          value_struct: null,
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 252977589148881,
        },
      ],
      differential_pricing: {
        id: 33580182,
      },
      original_price: null,
      category_id: "MLB437616",
      official_store_id: 1140,
      catalog_product_id: null,
      tags: [
        "brand_verified",
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB918281211",
      site_id: "MLB",
      title: "Diário De Anne Frank Livro Novo Lacrado Com Fotos Autenticas",
      seller: {
        id: 207333581,
        permalink: "http://perfil.mercadolivre.com.br/SPMIX+SHOP",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
        eshop: {
          nick_name: "SPMIX SHOP",
          eshop_rubro: null,
          eshop_id: 263849,
          eshop_locations: [],
          site_id: "MLB",
          eshop_logo_url:
            "http://resources.mlstatic.com/eshops/207333581v804e60.png",
          eshop_status_id: 1,
          seller: 207333581,
          eshop_experience: 0,
        },
      },
      price: 21.3,
      currency_id: "BRL",
      available_quantity: 3,
      sold_quantity: 500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2040-01-18T21:32:05.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-918281211-diario-de-anne-frank-livro-novo-lacrado-com-fotos-autenticas-_JM",
      thumbnail:
        "http://mlb-s2-p.mlstatic.com/761859-MLB31712575492_082019-I.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 4,
        amount: 5.77,
        rate: 8.31,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-31",
        city_name: "Osasco",
      },
      shipping: {
        free_shipping: false,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-31",
          name: "Osasco",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          value_id: "2230284",
          value_name: "Novo",
          values: [
            {
              source: 1,
              id: "2230284",
              name: "Novo",
              struct: null,
            },
          ],
          attribute_group_name: "Outros",
          source: 1,
          name: "Condição do item",
          value_struct: null,
          attribute_group_id: "OTHERS",
          id: "ITEM_CONDITION",
        },
      ],
      original_price: null,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "dragged_bids_and_visits",
        "poor_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB1234567890",
      site_id: "MLB",
      title: "1984 - George Orwell - Edição Especial",
      seller: {
        id: 123456789,
        permalink: "http://perfil.mercadolivre.com.br/LIVRARIA_CLASSICOS",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 45.9,
      currency_id: "BRL",
      available_quantity: 150,
      sold_quantity: 890,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-06-15T10:30:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-1234567890-1984-george-orwell-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/1984-cover-image.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 6,
        amount: 7.65,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-RJ",
        state_name: "Rio de Janeiro",
        city_id: "BR-RJ-01",
        city_name: "Rio de Janeiro",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-RJ",
          name: "Rio de Janeiro",
        },
        city: {
          id: "BR-RJ-01",
          name: "Rio de Janeiro",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 59.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB9876543210",
      site_id: "MLB",
      title: "Harry Potter E A Pedra Filosofal - J.K. Rowling",
      seller: {
        id: 987654321,
        permalink: "http://perfil.mercadolivre.com.br/MEGALIVRARIA",
        power_seller_status: "platinum",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 34.9,
      currency_id: "BRL",
      available_quantity: 200,
      sold_quantity: 1500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_pro",
      stop_time: "2039-03-20T14:45:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-9876543210-harry-potter-pedra-filosofal-_JM",
      thumbnail: "http://mlb-s2-p.mlstatic.com/harry-potter-1-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 3,
        amount: 11.63,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-MG",
        state_name: "Minas Gerais",
        city_id: "BR-MG-01",
        city_name: "Belo Horizonte",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: [],
        logistic_type: "default",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-MG",
          name: "Minas Gerais",
        },
        city: {
          id: "BR-MG-01",
          name: "Belo Horizonte",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: null,
      category_id: "MLB437616",
      official_store_id: 2001,
      catalog_product_id: null,
      tags: [
        "brand_verified",
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "best_seller",
      ],
    },
    {
      id: "MLB5555555555",
      site_id: "MLB",
      title: "O Senhor Dos Anéis - A Sociedade Do Anel",
      seller: {
        id: 555555555,
        permalink: "http://perfil.mercadolivre.com.br/LIVROS_FANTASTICOS",
        power_seller_status: "silver",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 52.9,
      currency_id: "BRL",
      available_quantity: 85,
      sold_quantity: 650,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-12-10T16:20:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-5555555555-senhor-aneis-sociedade-anel-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/lotr-fellowship-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 10,
        amount: 5.29,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-RS",
        state_name: "Rio Grande do Sul",
        city_id: "BR-RS-01",
        city_name: "Porto Alegre",
      },
      shipping: {
        free_shipping: false,
        mode: "me1",
        tags: [],
        logistic_type: "default",
        store_pick_up: true,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-RS",
          name: "Rio Grande do Sul",
        },
        city: {
          id: "BR-RS-01",
          name: "Porto Alegre",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 64.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: ["good_quality_picture", "immediate_payment", "cart_eligible"],
    },
    {
      id: "MLB7777777777",
      site_id: "MLB",
      title: "Dom Casmurro - Machado de Assis - Capa Dura",
      seller: {
        id: 777777777,
        permalink: "http://perfil.mercadolivre.com.br/LITERATURA_BRASILEIRA",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 29.9,
      currency_id: "BRL",
      available_quantity: 120,
      sold_quantity: 430,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-08-25T11:00:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-7777777777-dom-casmurro-machado-assis-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/dom-casmurro-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 5,
        amount: 5.98,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-50",
        city_name: "Campinas",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-50",
          name: "Campinas",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
        {
          id: "BOOK_GENRE",
          name: "Gênero do livro",
          value_name: "Literatura Brasileira",
          values: [
            {
              id: "2271780",
              name: "Literatura Brasileira",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2271780",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 39.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "classic",
      ],
    },

    {
      id: "MLB923744806",
      site_id: "MLB",
      title: "Pequeno Principe, O",
      seller: {
        id: 263929924,
        permalink: "http://perfil.mercadolivre.com.br/LIVRARIACULTURACULTURA",
        power_seller_status: "platinum",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 80.83,
      currency_id: "BRL",
      available_quantity: 500,
      sold_quantity: 500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_pro",
      stop_time: "2037-10-08T11:20:36.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-923744806-pequeno-principe-o-_JM",
      thumbnail:
        "http://mlb-s1-p.mlstatic.com/835599-MLB26167839876_102017-I.jpg",
      accepts_mercadopago: true,
      installments: null,
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-41",
        city_name: "Guarulhos",
      },
      shipping: {
        free_shipping: true,
        mode: "me1",
        tags: [],
        logistic_type: "default",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-41",
          name: "Guarulhos",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          values: [
            {
              id: null,
              name: "CAMINHO SUAVE ED.",
              struct: null,
              source: 252977589148881,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 252977589148881,
          id: "BRAND",
          value_id: null,
          value_struct: null,
          attribute_group_name: "Outros",
          name: "Marca",
          value_name: "CAMINHO SUAVE ED.",
        },
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          attribute_group_name: "Outros",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 1,
          value_id: "2230284",
          value_name: "Novo",
          value_struct: null,
        },
        {
          id: "MODEL",
          name: "Modelo",
          value_id: null,
          value_name: "Brochura",
          values: [
            {
              name: "Brochura",
              struct: null,
              source: 252977589148881,
              id: null,
            },
          ],
          value_struct: null,
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 252977589148881,
        },
      ],
      differential_pricing: {
        id: 33580182,
      },
      original_price: null,
      category_id: "MLB437616",
      official_store_id: 1140,
      catalog_product_id: null,
      tags: [
        "brand_verified",
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB918281211",
      site_id: "MLB",
      title: "Diário De Anne Frank Livro Novo Lacrado Com Fotos Autenticas",
      seller: {
        id: 207333581,
        permalink: "http://perfil.mercadolivre.com.br/SPMIX+SHOP",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
        eshop: {
          nick_name: "SPMIX SHOP",
          eshop_rubro: null,
          eshop_id: 263849,
          eshop_locations: [],
          site_id: "MLB",
          eshop_logo_url:
            "http://resources.mlstatic.com/eshops/207333581v804e60.png",
          eshop_status_id: 1,
          seller: 207333581,
          eshop_experience: 0,
        },
      },
      price: 21.3,
      currency_id: "BRL",
      available_quantity: 3,
      sold_quantity: 500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2040-01-18T21:32:05.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-918281211-diario-de-anne-frank-livro-novo-lacrado-com-fotos-autenticas-_JM",
      thumbnail:
        "http://mlb-s2-p.mlstatic.com/761859-MLB31712575492_082019-I.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 4,
        amount: 5.77,
        rate: 8.31,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-31",
        city_name: "Osasco",
      },
      shipping: {
        free_shipping: false,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-31",
          name: "Osasco",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          value_id: "2230284",
          value_name: "Novo",
          values: [
            {
              source: 1,
              id: "2230284",
              name: "Novo",
              struct: null,
            },
          ],
          attribute_group_name: "Outros",
          source: 1,
          name: "Condição do item",
          value_struct: null,
          attribute_group_id: "OTHERS",
          id: "ITEM_CONDITION",
        },
      ],
      original_price: null,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "dragged_bids_and_visits",
        "poor_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB1234567890",
      site_id: "MLB",
      title: "1984 - George Orwell - Edição Especial",
      seller: {
        id: 123456789,
        permalink: "http://perfil.mercadolivre.com.br/LIVRARIA_CLASSICOS",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 45.9,
      currency_id: "BRL",
      available_quantity: 150,
      sold_quantity: 890,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-06-15T10:30:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-1234567890-1984-george-orwell-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/1984-cover-image.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 6,
        amount: 7.65,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-RJ",
        state_name: "Rio de Janeiro",
        city_id: "BR-RJ-01",
        city_name: "Rio de Janeiro",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-RJ",
          name: "Rio de Janeiro",
        },
        city: {
          id: "BR-RJ-01",
          name: "Rio de Janeiro",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 59.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB9876543210",
      site_id: "MLB",
      title: "Harry Potter E A Pedra Filosofal - J.K. Rowling",
      seller: {
        id: 987654321,
        permalink: "http://perfil.mercadolivre.com.br/MEGALIVRARIA",
        power_seller_status: "platinum",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 34.9,
      currency_id: "BRL",
      available_quantity: 200,
      sold_quantity: 1500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_pro",
      stop_time: "2039-03-20T14:45:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-9876543210-harry-potter-pedra-filosofal-_JM",
      thumbnail: "http://mlb-s2-p.mlstatic.com/harry-potter-1-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 3,
        amount: 11.63,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-MG",
        state_name: "Minas Gerais",
        city_id: "BR-MG-01",
        city_name: "Belo Horizonte",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: [],
        logistic_type: "default",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-MG",
          name: "Minas Gerais",
        },
        city: {
          id: "BR-MG-01",
          name: "Belo Horizonte",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: null,
      category_id: "MLB437616",
      official_store_id: 2001,
      catalog_product_id: null,
      tags: [
        "brand_verified",
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "best_seller",
      ],
    },
    {
      id: "MLB5555555555",
      site_id: "MLB",
      title: "O Senhor Dos Anéis - A Sociedade Do Anel",
      seller: {
        id: 555555555,
        permalink: "http://perfil.mercadolivre.com.br/LIVROS_FANTASTICOS",
        power_seller_status: "silver",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 52.9,
      currency_id: "BRL",
      available_quantity: 85,
      sold_quantity: 650,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-12-10T16:20:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-5555555555-senhor-aneis-sociedade-anel-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/lotr-fellowship-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 10,
        amount: 5.29,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-RS",
        state_name: "Rio Grande do Sul",
        city_id: "BR-RS-01",
        city_name: "Porto Alegre",
      },
      shipping: {
        free_shipping: false,
        mode: "me1",
        tags: [],
        logistic_type: "default",
        store_pick_up: true,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-RS",
          name: "Rio Grande do Sul",
        },
        city: {
          id: "BR-RS-01",
          name: "Porto Alegre",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 64.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: ["good_quality_picture", "immediate_payment", "cart_eligible"],
    },
    {
      id: "MLB7777777777",
      site_id: "MLB",
      title: "Dom Casmurro - Machado de Assis - Capa Dura",
      seller: {
        id: 777777777,
        permalink: "http://perfil.mercadolivre.com.br/LITERATURA_BRASILEIRA",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 29.9,
      currency_id: "BRL",
      available_quantity: 120,
      sold_quantity: 430,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-08-25T11:00:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-7777777777-dom-casmurro-machado-assis-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/dom-casmurro-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 5,
        amount: 5.98,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-50",
        city_name: "Campinas",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-50",
          name: "Campinas",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
        {
          id: "BOOK_GENRE",
          name: "Gênero do livro",
          value_name: "Literatura Brasileira",
          values: [
            {
              id: "2271780",
              name: "Literatura Brasileira",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2271780",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 39.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "classic",
      ],
    },

    {
      id: "MLB923744806",
      site_id: "MLB",
      title: "Pequeno Principe, O",
      seller: {
        id: 263929924,
        permalink: "http://perfil.mercadolivre.com.br/LIVRARIACULTURACULTURA",
        power_seller_status: "platinum",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 80.83,
      currency_id: "BRL",
      available_quantity: 500,
      sold_quantity: 500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_pro",
      stop_time: "2037-10-08T11:20:36.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-923744806-pequeno-principe-o-_JM",
      thumbnail:
        "http://mlb-s1-p.mlstatic.com/835599-MLB26167839876_102017-I.jpg",
      accepts_mercadopago: true,
      installments: null,
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-41",
        city_name: "Guarulhos",
      },
      shipping: {
        free_shipping: true,
        mode: "me1",
        tags: [],
        logistic_type: "default",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-41",
          name: "Guarulhos",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          values: [
            {
              id: null,
              name: "CAMINHO SUAVE ED.",
              struct: null,
              source: 252977589148881,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 252977589148881,
          id: "BRAND",
          value_id: null,
          value_struct: null,
          attribute_group_name: "Outros",
          name: "Marca",
          value_name: "CAMINHO SUAVE ED.",
        },
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          attribute_group_name: "Outros",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 1,
          value_id: "2230284",
          value_name: "Novo",
          value_struct: null,
        },
        {
          id: "MODEL",
          name: "Modelo",
          value_id: null,
          value_name: "Brochura",
          values: [
            {
              name: "Brochura",
              struct: null,
              source: 252977589148881,
              id: null,
            },
          ],
          value_struct: null,
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 252977589148881,
        },
      ],
      differential_pricing: {
        id: 33580182,
      },
      original_price: null,
      category_id: "MLB437616",
      official_store_id: 1140,
      catalog_product_id: null,
      tags: [
        "brand_verified",
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB918281211",
      site_id: "MLB",
      title: "Diário De Anne Frank Livro Novo Lacrado Com Fotos Autenticas",
      seller: {
        id: 207333581,
        permalink: "http://perfil.mercadolivre.com.br/SPMIX+SHOP",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
        eshop: {
          nick_name: "SPMIX SHOP",
          eshop_rubro: null,
          eshop_id: 263849,
          eshop_locations: [],
          site_id: "MLB",
          eshop_logo_url:
            "http://resources.mlstatic.com/eshops/207333581v804e60.png",
          eshop_status_id: 1,
          seller: 207333581,
          eshop_experience: 0,
        },
      },
      price: 21.3,
      currency_id: "BRL",
      available_quantity: 3,
      sold_quantity: 500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2040-01-18T21:32:05.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-918281211-diario-de-anne-frank-livro-novo-lacrado-com-fotos-autenticas-_JM",
      thumbnail:
        "http://mlb-s2-p.mlstatic.com/761859-MLB31712575492_082019-I.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 4,
        amount: 5.77,
        rate: 8.31,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-31",
        city_name: "Osasco",
      },
      shipping: {
        free_shipping: false,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-31",
          name: "Osasco",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          value_id: "2230284",
          value_name: "Novo",
          values: [
            {
              source: 1,
              id: "2230284",
              name: "Novo",
              struct: null,
            },
          ],
          attribute_group_name: "Outros",
          source: 1,
          name: "Condição do item",
          value_struct: null,
          attribute_group_id: "OTHERS",
          id: "ITEM_CONDITION",
        },
      ],
      original_price: null,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "dragged_bids_and_visits",
        "poor_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB1234567890",
      site_id: "MLB",
      title: "1984 - George Orwell - Edição Especial",
      seller: {
        id: 123456789,
        permalink: "http://perfil.mercadolivre.com.br/LIVRARIA_CLASSICOS",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 45.9,
      currency_id: "BRL",
      available_quantity: 150,
      sold_quantity: 890,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-06-15T10:30:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-1234567890-1984-george-orwell-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/1984-cover-image.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 6,
        amount: 7.65,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-RJ",
        state_name: "Rio de Janeiro",
        city_id: "BR-RJ-01",
        city_name: "Rio de Janeiro",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-RJ",
          name: "Rio de Janeiro",
        },
        city: {
          id: "BR-RJ-01",
          name: "Rio de Janeiro",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 59.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB9876543210",
      site_id: "MLB",
      title: "Harry Potter E A Pedra Filosofal - J.K. Rowling",
      seller: {
        id: 987654321,
        permalink: "http://perfil.mercadolivre.com.br/MEGALIVRARIA",
        power_seller_status: "platinum",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 34.9,
      currency_id: "BRL",
      available_quantity: 200,
      sold_quantity: 1500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_pro",
      stop_time: "2039-03-20T14:45:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-9876543210-harry-potter-pedra-filosofal-_JM",
      thumbnail: "http://mlb-s2-p.mlstatic.com/harry-potter-1-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 3,
        amount: 11.63,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-MG",
        state_name: "Minas Gerais",
        city_id: "BR-MG-01",
        city_name: "Belo Horizonte",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: [],
        logistic_type: "default",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-MG",
          name: "Minas Gerais",
        },
        city: {
          id: "BR-MG-01",
          name: "Belo Horizonte",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: null,
      category_id: "MLB437616",
      official_store_id: 2001,
      catalog_product_id: null,
      tags: [
        "brand_verified",
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "best_seller",
      ],
    },
    {
      id: "MLB5555555555",
      site_id: "MLB",
      title: "O Senhor Dos Anéis - A Sociedade Do Anel",
      seller: {
        id: 555555555,
        permalink: "http://perfil.mercadolivre.com.br/LIVROS_FANTASTICOS",
        power_seller_status: "silver",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 52.9,
      currency_id: "BRL",
      available_quantity: 85,
      sold_quantity: 650,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-12-10T16:20:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-5555555555-senhor-aneis-sociedade-anel-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/lotr-fellowship-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 10,
        amount: 5.29,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-RS",
        state_name: "Rio Grande do Sul",
        city_id: "BR-RS-01",
        city_name: "Porto Alegre",
      },
      shipping: {
        free_shipping: false,
        mode: "me1",
        tags: [],
        logistic_type: "default",
        store_pick_up: true,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-RS",
          name: "Rio Grande do Sul",
        },
        city: {
          id: "BR-RS-01",
          name: "Porto Alegre",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 64.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: ["good_quality_picture", "immediate_payment", "cart_eligible"],
    },
    {
      id: "MLB7777777777",
      site_id: "MLB",
      title: "Dom Casmurro - Machado de Assis - Capa Dura",
      seller: {
        id: 777777777,
        permalink: "http://perfil.mercadolivre.com.br/LITERATURA_BRASILEIRA",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 29.9,
      currency_id: "BRL",
      available_quantity: 120,
      sold_quantity: 430,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-08-25T11:00:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-7777777777-dom-casmurro-machado-assis-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/dom-casmurro-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 5,
        amount: 5.98,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-50",
        city_name: "Campinas",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-50",
          name: "Campinas",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
        {
          id: "BOOK_GENRE",
          name: "Gênero do livro",
          value_name: "Literatura Brasileira",
          values: [
            {
              id: "2271780",
              name: "Literatura Brasileira",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2271780",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 39.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "classic",
      ],
    },

    {
      id: "MLB923744806",
      site_id: "MLB",
      title: "Pequeno Principe, O",
      seller: {
        id: 263929924,
        permalink: "http://perfil.mercadolivre.com.br/LIVRARIACULTURACULTURA",
        power_seller_status: "platinum",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 80.83,
      currency_id: "BRL",
      available_quantity: 500,
      sold_quantity: 500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_pro",
      stop_time: "2037-10-08T11:20:36.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-923744806-pequeno-principe-o-_JM",
      thumbnail:
        "http://mlb-s1-p.mlstatic.com/835599-MLB26167839876_102017-I.jpg",
      accepts_mercadopago: true,
      installments: null,
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-41",
        city_name: "Guarulhos",
      },
      shipping: {
        free_shipping: true,
        mode: "me1",
        tags: [],
        logistic_type: "default",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-41",
          name: "Guarulhos",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          values: [
            {
              id: null,
              name: "CAMINHO SUAVE ED.",
              struct: null,
              source: 252977589148881,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 252977589148881,
          id: "BRAND",
          value_id: null,
          value_struct: null,
          attribute_group_name: "Outros",
          name: "Marca",
          value_name: "CAMINHO SUAVE ED.",
        },
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          attribute_group_name: "Outros",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 1,
          value_id: "2230284",
          value_name: "Novo",
          value_struct: null,
        },
        {
          id: "MODEL",
          name: "Modelo",
          value_id: null,
          value_name: "Brochura",
          values: [
            {
              name: "Brochura",
              struct: null,
              source: 252977589148881,
              id: null,
            },
          ],
          value_struct: null,
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 252977589148881,
        },
      ],
      differential_pricing: {
        id: 33580182,
      },
      original_price: null,
      category_id: "MLB437616",
      official_store_id: 1140,
      catalog_product_id: null,
      tags: [
        "brand_verified",
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB918281211",
      site_id: "MLB",
      title: "Diário De Anne Frank Livro Novo Lacrado Com Fotos Autenticas",
      seller: {
        id: 207333581,
        permalink: "http://perfil.mercadolivre.com.br/SPMIX+SHOP",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
        eshop: {
          nick_name: "SPMIX SHOP",
          eshop_rubro: null,
          eshop_id: 263849,
          eshop_locations: [],
          site_id: "MLB",
          eshop_logo_url:
            "http://resources.mlstatic.com/eshops/207333581v804e60.png",
          eshop_status_id: 1,
          seller: 207333581,
          eshop_experience: 0,
        },
      },
      price: 21.3,
      currency_id: "BRL",
      available_quantity: 3,
      sold_quantity: 500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2040-01-18T21:32:05.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-918281211-diario-de-anne-frank-livro-novo-lacrado-com-fotos-autenticas-_JM",
      thumbnail:
        "http://mlb-s2-p.mlstatic.com/761859-MLB31712575492_082019-I.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 4,
        amount: 5.77,
        rate: 8.31,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-31",
        city_name: "Osasco",
      },
      shipping: {
        free_shipping: false,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-31",
          name: "Osasco",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          value_id: "2230284",
          value_name: "Novo",
          values: [
            {
              source: 1,
              id: "2230284",
              name: "Novo",
              struct: null,
            },
          ],
          attribute_group_name: "Outros",
          source: 1,
          name: "Condição do item",
          value_struct: null,
          attribute_group_id: "OTHERS",
          id: "ITEM_CONDITION",
        },
      ],
      original_price: null,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "dragged_bids_and_visits",
        "poor_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB1234567890",
      site_id: "MLB",
      title: "1984 - George Orwell - Edição Especial",
      seller: {
        id: 123456789,
        permalink: "http://perfil.mercadolivre.com.br/LIVRARIA_CLASSICOS",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 45.9,
      currency_id: "BRL",
      available_quantity: 150,
      sold_quantity: 890,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-06-15T10:30:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-1234567890-1984-george-orwell-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/1984-cover-image.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 6,
        amount: 7.65,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-RJ",
        state_name: "Rio de Janeiro",
        city_id: "BR-RJ-01",
        city_name: "Rio de Janeiro",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-RJ",
          name: "Rio de Janeiro",
        },
        city: {
          id: "BR-RJ-01",
          name: "Rio de Janeiro",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 59.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB9876543210",
      site_id: "MLB",
      title: "Harry Potter E A Pedra Filosofal - J.K. Rowling",
      seller: {
        id: 987654321,
        permalink: "http://perfil.mercadolivre.com.br/MEGALIVRARIA",
        power_seller_status: "platinum",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 34.9,
      currency_id: "BRL",
      available_quantity: 200,
      sold_quantity: 1500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_pro",
      stop_time: "2039-03-20T14:45:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-9876543210-harry-potter-pedra-filosofal-_JM",
      thumbnail: "http://mlb-s2-p.mlstatic.com/harry-potter-1-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 3,
        amount: 11.63,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-MG",
        state_name: "Minas Gerais",
        city_id: "BR-MG-01",
        city_name: "Belo Horizonte",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: [],
        logistic_type: "default",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-MG",
          name: "Minas Gerais",
        },
        city: {
          id: "BR-MG-01",
          name: "Belo Horizonte",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: null,
      category_id: "MLB437616",
      official_store_id: 2001,
      catalog_product_id: null,
      tags: [
        "brand_verified",
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "best_seller",
      ],
    },
    {
      id: "MLB5555555555",
      site_id: "MLB",
      title: "O Senhor Dos Anéis - A Sociedade Do Anel",
      seller: {
        id: 555555555,
        permalink: "http://perfil.mercadolivre.com.br/LIVROS_FANTASTICOS",
        power_seller_status: "silver",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 52.9,
      currency_id: "BRL",
      available_quantity: 85,
      sold_quantity: 650,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-12-10T16:20:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-5555555555-senhor-aneis-sociedade-anel-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/lotr-fellowship-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 10,
        amount: 5.29,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-RS",
        state_name: "Rio Grande do Sul",
        city_id: "BR-RS-01",
        city_name: "Porto Alegre",
      },
      shipping: {
        free_shipping: false,
        mode: "me1",
        tags: [],
        logistic_type: "default",
        store_pick_up: true,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-RS",
          name: "Rio Grande do Sul",
        },
        city: {
          id: "BR-RS-01",
          name: "Porto Alegre",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 64.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: ["good_quality_picture", "immediate_payment", "cart_eligible"],
    },
    {
      id: "MLB7777777777",
      site_id: "MLB",
      title: "Dom Casmurro - Machado de Assis - Capa Dura",
      seller: {
        id: 777777777,
        permalink: "http://perfil.mercadolivre.com.br/LITERATURA_BRASILEIRA",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 29.9,
      currency_id: "BRL",
      available_quantity: 120,
      sold_quantity: 430,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-08-25T11:00:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-7777777777-dom-casmurro-machado-assis-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/dom-casmurro-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 5,
        amount: 5.98,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-50",
        city_name: "Campinas",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-50",
          name: "Campinas",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
        {
          id: "BOOK_GENRE",
          name: "Gênero do livro",
          value_name: "Literatura Brasileira",
          values: [
            {
              id: "2271780",
              name: "Literatura Brasileira",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2271780",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 39.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "classic",
      ],
    },

    {
      id: "MLB923744806",
      site_id: "MLB",
      title: "Pequeno Principe, O",
      seller: {
        id: 263929924,
        permalink: "http://perfil.mercadolivre.com.br/LIVRARIACULTURACULTURA",
        power_seller_status: "platinum",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 80.83,
      currency_id: "BRL",
      available_quantity: 500,
      sold_quantity: 500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_pro",
      stop_time: "2037-10-08T11:20:36.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-923744806-pequeno-principe-o-_JM",
      thumbnail:
        "http://mlb-s1-p.mlstatic.com/835599-MLB26167839876_102017-I.jpg",
      accepts_mercadopago: true,
      installments: null,
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-41",
        city_name: "Guarulhos",
      },
      shipping: {
        free_shipping: true,
        mode: "me1",
        tags: [],
        logistic_type: "default",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-41",
          name: "Guarulhos",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          values: [
            {
              id: null,
              name: "CAMINHO SUAVE ED.",
              struct: null,
              source: 252977589148881,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 252977589148881,
          id: "BRAND",
          value_id: null,
          value_struct: null,
          attribute_group_name: "Outros",
          name: "Marca",
          value_name: "CAMINHO SUAVE ED.",
        },
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          attribute_group_name: "Outros",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          source: 1,
          value_id: "2230284",
          value_name: "Novo",
          value_struct: null,
        },
        {
          id: "MODEL",
          name: "Modelo",
          value_id: null,
          value_name: "Brochura",
          values: [
            {
              name: "Brochura",
              struct: null,
              source: 252977589148881,
              id: null,
            },
          ],
          value_struct: null,
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 252977589148881,
        },
      ],
      differential_pricing: {
        id: 33580182,
      },
      original_price: null,
      category_id: "MLB437616",
      official_store_id: 1140,
      catalog_product_id: null,
      tags: [
        "brand_verified",
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB918281211",
      site_id: "MLB",
      title: "Diário De Anne Frank Livro Novo Lacrado Com Fotos Autenticas",
      seller: {
        id: 207333581,
        permalink: "http://perfil.mercadolivre.com.br/SPMIX+SHOP",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
        eshop: {
          nick_name: "SPMIX SHOP",
          eshop_rubro: null,
          eshop_id: 263849,
          eshop_locations: [],
          site_id: "MLB",
          eshop_logo_url:
            "http://resources.mlstatic.com/eshops/207333581v804e60.png",
          eshop_status_id: 1,
          seller: 207333581,
          eshop_experience: 0,
        },
      },
      price: 21.3,
      currency_id: "BRL",
      available_quantity: 3,
      sold_quantity: 500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2040-01-18T21:32:05.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-918281211-diario-de-anne-frank-livro-novo-lacrado-com-fotos-autenticas-_JM",
      thumbnail:
        "http://mlb-s2-p.mlstatic.com/761859-MLB31712575492_082019-I.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 4,
        amount: 5.77,
        rate: 8.31,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-31",
        city_name: "Osasco",
      },
      shipping: {
        free_shipping: false,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-31",
          name: "Osasco",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          value_id: "2230284",
          value_name: "Novo",
          values: [
            {
              source: 1,
              id: "2230284",
              name: "Novo",
              struct: null,
            },
          ],
          attribute_group_name: "Outros",
          source: 1,
          name: "Condição do item",
          value_struct: null,
          attribute_group_id: "OTHERS",
          id: "ITEM_CONDITION",
        },
      ],
      original_price: null,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "dragged_bids_and_visits",
        "poor_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB1234567890",
      site_id: "MLB",
      title: "1984 - George Orwell - Edição Especial",
      seller: {
        id: 123456789,
        permalink: "http://perfil.mercadolivre.com.br/LIVRARIA_CLASSICOS",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 45.9,
      currency_id: "BRL",
      available_quantity: 150,
      sold_quantity: 890,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-06-15T10:30:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-1234567890-1984-george-orwell-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/1984-cover-image.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 6,
        amount: 7.65,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-RJ",
        state_name: "Rio de Janeiro",
        city_id: "BR-RJ-01",
        city_name: "Rio de Janeiro",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-RJ",
          name: "Rio de Janeiro",
        },
        city: {
          id: "BR-RJ-01",
          name: "Rio de Janeiro",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 59.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
      ],
    },
    {
      id: "MLB9876543210",
      site_id: "MLB",
      title: "Harry Potter E A Pedra Filosofal - J.K. Rowling",
      seller: {
        id: 987654321,
        permalink: "http://perfil.mercadolivre.com.br/MEGALIVRARIA",
        power_seller_status: "platinum",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 34.9,
      currency_id: "BRL",
      available_quantity: 200,
      sold_quantity: 1500,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_pro",
      stop_time: "2039-03-20T14:45:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-9876543210-harry-potter-pedra-filosofal-_JM",
      thumbnail: "http://mlb-s2-p.mlstatic.com/harry-potter-1-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 3,
        amount: 11.63,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-MG",
        state_name: "Minas Gerais",
        city_id: "BR-MG-01",
        city_name: "Belo Horizonte",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: [],
        logistic_type: "default",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-MG",
          name: "Minas Gerais",
        },
        city: {
          id: "BR-MG-01",
          name: "Belo Horizonte",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: null,
      category_id: "MLB437616",
      official_store_id: 2001,
      catalog_product_id: null,
      tags: [
        "brand_verified",
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "best_seller",
      ],
    },
    {
      id: "MLB5555555555",
      site_id: "MLB",
      title: "O Senhor Dos Anéis - A Sociedade Do Anel",
      seller: {
        id: 555555555,
        permalink: "http://perfil.mercadolivre.com.br/LIVROS_FANTASTICOS",
        power_seller_status: "silver",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 52.9,
      currency_id: "BRL",
      available_quantity: 85,
      sold_quantity: 650,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-12-10T16:20:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-5555555555-senhor-aneis-sociedade-anel-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/lotr-fellowship-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 10,
        amount: 5.29,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-RS",
        state_name: "Rio Grande do Sul",
        city_id: "BR-RS-01",
        city_name: "Porto Alegre",
      },
      shipping: {
        free_shipping: false,
        mode: "me1",
        tags: [],
        logistic_type: "default",
        store_pick_up: true,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-RS",
          name: "Rio Grande do Sul",
        },
        city: {
          id: "BR-RS-01",
          name: "Porto Alegre",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 64.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: ["good_quality_picture", "immediate_payment", "cart_eligible"],
    },
    {
      id: "MLB7777777777",
      site_id: "MLB",
      title: "Dom Casmurro - Machado de Assis - Capa Dura",
      seller: {
        id: 777777777,
        permalink: "http://perfil.mercadolivre.com.br/LITERATURA_BRASILEIRA",
        power_seller_status: "gold",
        car_dealer: false,
        real_estate_agency: false,
        tags: [],
      },
      price: 29.9,
      currency_id: "BRL",
      available_quantity: 120,
      sold_quantity: 430,
      buying_mode: "buy_it_now",
      listing_type_id: "gold_special",
      stop_time: "2038-08-25T11:00:00.000Z",
      condition: "new",
      permalink:
        "https://produto.mercadolivre.com.br/MLB-7777777777-dom-casmurro-machado-assis-_JM",
      thumbnail: "http://mlb-s1-p.mlstatic.com/dom-casmurro-cover.jpg",
      accepts_mercadopago: true,
      installments: {
        quantity: 5,
        amount: 5.98,
        rate: 0,
        currency_id: "BRL",
      },
      address: {
        state_id: "BR-SP",
        state_name: "São Paulo",
        city_id: "BR-SP-50",
        city_name: "Campinas",
      },
      shipping: {
        free_shipping: true,
        mode: "me2",
        tags: ["fulfillment"],
        logistic_type: "fulfillment",
        store_pick_up: false,
      },
      seller_address: {
        id: "",
        comment: "",
        address_line: "",
        zip_code: "",
        country: {
          id: "BR",
          name: "Brasil",
        },
        state: {
          id: "BR-SP",
          name: "São Paulo",
        },
        city: {
          id: "BR-SP-50",
          name: "Campinas",
        },
        latitude: "",
        longitude: "",
      },
      attributes: [
        {
          id: "ITEM_CONDITION",
          name: "Condição do item",
          value_name: "Novo",
          values: [
            {
              id: "2230284",
              name: "Novo",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2230284",
          value_struct: null,
        },
        {
          id: "BOOK_GENRE",
          name: "Gênero do livro",
          value_name: "Literatura Brasileira",
          values: [
            {
              id: "2271780",
              name: "Literatura Brasileira",
              struct: null,
              source: 1,
            },
          ],
          attribute_group_id: "OTHERS",
          attribute_group_name: "Outros",
          source: 1,
          value_id: "2271780",
          value_struct: null,
        },
      ],
      differential_pricing: null,
      original_price: 39.9,
      category_id: "MLB437616",
      official_store_id: null,
      catalog_product_id: null,
      tags: [
        "good_quality_picture",
        "immediate_payment",
        "cart_eligible",
        "shipping_guaranteed",
        "classic",
      ],
    },
  ],
  secondary_results: [],
  related_results: [],
  sort: {
    id: "relevance",
    name: "Mais relevantes",
  },
  available_sorts: [
    {
      id: "price_asc",
      name: "Menor preço",
    },
    {
      id: "price_desc",
      name: "Maior preço",
    },
  ],
  filters: [] as any[],
  available_filters: [] as any[],
};

export default queryMock;
